[package]
name = "sound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-thread = "0.1.2"
cpal = {version = "0.13.5"}
eframe = {version = "0.18.0", features = ["dark-light"]}
